vowels = [ "ğ‘€…", "ğ‘€†", "ğ‘€‡", "ğ‘€ˆ", "ğ‘€‰", "ğ‘€Š", "ğ‘€‹", "ğ‘€Œ", "ğ‘€", "ğ‘€", "ğ‘€ğ‘†", "ğ‘€", "ğ‘€", "ğ‘€‘ğ‘†", "ğ‘€‘", "ğ‘€’",]
vowel_marks = [ "ğ‘€¸", "ğ‘€º", "ğ‘€»", "ğ‘€¼", "ğ‘€½", "ğ‘€¾", "ğ‘€¿", "ğ‘€", "ğ‘", "ğ‘‚", "ğ‘‚", "ğ‘ƒ", "ğ‘„", "ğ‘„", "ğ‘…",]
yogavaahas = [ "ğ‘€", "ğ‘€‚", "ğ‘€€",]
virama = [ "ğ‘†",]
consonants = [ "ğ‘€“", "ğ‘€”", "ğ‘€•", "ğ‘€–", "ğ‘€—", "ğ‘€˜", "ğ‘€™", "ğ‘€š", "ğ‘€›", "ğ‘€œ", "ğ‘€", "ğ‘€", "ğ‘€Ÿ", "ğ‘€ ", "ğ‘€¡", "ğ‘€¢", "ğ‘€£", "ğ‘€¤", "ğ‘€¥", "ğ‘€¦", "ğ‘€§", "ğ‘€¨", "ğ‘€©", "ğ‘€ª", "ğ‘€«", "ğ‘€¬", "ğ‘€­", "ğ‘€®", "ğ‘€¯", "ğ‘€°", "ğ‘€±", "ğ‘€²", "ğ‘€³", "ğ‘€´", "ğ‘€“ğ‘†ğ‘€±", "ğ‘€šğ‘†ğ‘€œ",]
symbols = [ "ğ‘¦", "ğ‘§", "ğ‘¨", "ğ‘©", "ğ‘ª", "ğ‘«", "ğ‘¬", "ğ‘­", "ğ‘®", "ğ‘¯", "ğ‘€‘ğ‘€", "", "ğ‘‡", "ğ‘ˆ",]
zwj = [ "\u200d",]
skip = [ "",]
accents = [ "à¥‘", "à¥’",]
candra = [ "ğ‘‚",]
extra_consonants = [ "ğ‘€“", "ğ‘€”", "ğ‘€•", "ğ‘€š", "ğ‘€Ÿ", "ğ‘€ ", "ğ‘€¨", "ğ‘€¬", "ğ‘€­",]
