vowels = [ "ğ‘€…", "ğ‘€†", "ğ‘€‡", "ğ‘€ˆ", "ğ‘€‰", "ğ‘€Š", "ğ‘€­ğ‘€¼", "ğ‘€­ğ‘€½", "ğ‘€®ğ‘€¼", "ğ‘€®ğ‘€½", "ğ‘€ğ‘†", "ğ‘€", "ğ‘€", "ğ‘€‘ğ‘†", "ğ‘€‘", "ğ‘€’",]
vowel_marks = [ "ğ‘€¸", "ğ‘€º", "ğ‘€»", "ğ‘€¼", "ğ‘€½", "ğ‘†ğ‘€­ğ‘€¼", "ğ‘†ğ‘€­ğ‘€½", "ğ‘†ğ‘€®ğ‘€¼", "ğ‘†ğ‘€®ğ‘€½", "ğ‘‚ğ‘†", "ğ‘‚", "ğ‘ƒ", "ğ‘„ğ‘†", "ğ‘„", "ğ‘…",]
yogavaahas = [ "ğ‘€«ğ‘†", "ğ‘€‚", "ğ‘€«ğ‘†",]
virama = [ "ğ‘†",]
consonants = [ "ğ‘€“", "ğ‘€“", "ğ‘€“", "ğ‘€“", "ğ‘€—", "ğ‘€˜", "ğ‘€˜", "ğ‘€š", "ğ‘€š", "ğ‘€œ", "ğ‘€", "ğ‘€", "ğ‘€", "ğ‘€", "ğ‘€¡", "ğ‘€¢", "ğ‘€¢", "ğ‘€¢", "ğ‘€¥", "ğ‘€¦", "ğ‘€§", "ğ‘€§", "ğ‘€§", "ğ‘€§", "ğ‘€«", "ğ‘€¬", "ğ‘€­", "ğ‘€®", "ğ‘€¯", "ğ‘€°", "ğ‘€±", "ğ‘€²", "ğ‘€³", "ğ‘€´", "ğ‘€“ğ‘†ğ‘€±", "ğ‘€šğ‘†ğ‘€œ",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ğ‘€‘ğ‘€«ğ‘†", "'", ".", "..",]
candra = [ "ğ‘‚ğ‘†",]
extra_consonants = [ "ğ‘€“", "ğ‘€“", "ğ‘€“", "ğ‘€š", "ğ‘€", "ğ‘€", "ğ‘€§", "ğ‘€¬", "ğ‘€¶",]
