vowels = [ "ğ‘Œ…", "ğ‘Œ†", "ğ‘Œ‡", "ğ‘Œˆ", "ğ‘Œ‰", "ğ‘ŒŠ", "ğ‘Œ‹", "ğ‘ ", "ğ‘ŒŒ", "ğ‘¡", "ğ‘Œğ‘Œ€", "ğ‘Œ", "ğ‘Œ", "ğ‘Œ“ğ‘Œ€", "ğ‘Œ“", "ğ‘Œ”",]
vowel_marks = [ "ğ‘Œ¾", "ğ‘Œ¿", "ğ‘€", "ğ‘", "ğ‘‚", "ğ‘ƒ", "ğ‘„", "ğ‘¢", "ğ‘£", "ğ‘‡ğ‘Œ€", "ğ‘‡", "ğ‘ˆ", "ğ‘‹ğ‘Œ€", "ğ‘‹", "ğ‘—",]
yogavaahas = [ "ğ‘Œ‚", "ğ‘Œƒ", "ğ‘Œ",]
virama = [ "ğ‘",]
consonants = [ "ğ‘Œ•", "ğ‘Œ–", "ğ‘Œ—", "ğ‘Œ˜", "ğ‘Œ™", "ğ‘Œš", "ğ‘Œ›", "ğ‘Œœ", "ğ‘Œ", "ğ‘Œ", "ğ‘ŒŸ", "ğ‘Œ ", "ğ‘Œ¡", "ğ‘Œ¢", "ğ‘Œ£", "ğ‘Œ¤", "ğ‘Œ¥", "ğ‘Œ¦", "ğ‘Œ§", "ğ‘Œ¨", "ğ‘Œª", "ğ‘Œ«", "ğ‘Œ¬", "ğ‘Œ­", "ğ‘Œ®", "ğ‘Œ¯", "ğ‘Œ°", "ğ‘Œ²", "ğ‘Œµ", "ğ‘Œ¶", "ğ‘Œ·", "ğ‘Œ¸", "ğ‘Œ¹", "ğ‘Œ³", "ğ‘Œ•ğ‘ğ‘Œ·", "ğ‘Œœğ‘ğ‘Œ",]
symbols = [ "à¯¦", "à¯§", "à¯¨", "à¯©", "à¯ª", "à¯«", "à¯¬", "à¯­", "à¯®", "à¯¯", "ğ‘", "ğ‘Œ½", "à¥¤", "à¥¥",]
candra = [ "ğ‘‡",]
extra_consonants = [ "ğ‘Œ•ğ‘Œ¼", "ğ‘Œ–ğ‘Œ¼", "ğ‘Œ—ğ‘Œ¼", "ğ‘Œœğ‘Œ¼", "ğ‘Œ¡ğ‘Œ¼", "ğ‘Œ¢ğ‘Œ¼", "ğ‘Œ«ğ‘Œ¼", "ğ‘Œ¯ğ‘Œ¼", "ğ‘Œ°ğ‘Œ¼",]
