vowels = [ "π‘°", "π‘±", "π‘²", "π‘³", "π‘΄", "π‘µ", "π‘‹™π‘‹΅", "π‘‹™π‘‹Ά", "π‘‹π‘‹΅", "π‘‹π‘‹Ά", "", "π‘¶", "π‘·", "", "π‘Έ", "π‘Ή",]
vowel_marks = [ "π‘‹ ", "π‘‹΅", "π‘‹Ά", "π‘‹£", "π‘‹¤", "π‘‹π‘‹™π‘‹΅", "π‘‹π‘‹™π‘‹Ά", "π‘‹π‘‹π‘‹΅", "π‘‹π‘‹π‘‹Ά", "", "π‘‹¥", "π‘‹¦", "", "π‘‹§", "π‘‹¨",]
yogavaahas = [ "π‘‹", "π‘‹π‘‹", "π‘‹",]
virama = [ "π‘‹",]
consonants = [ "π‘Ί", "π‘»", "π‘Ό", "π‘Ύ", "π‘Ώ", "π‘‹€", "π‘‹", "π‘‹‚", "π‘‹„", "π‘‹…", "π‘‹†", "π‘‹‡", "π‘‹", "π‘‹‹", "π‘‹", "π‘‹", "π‘‹", "π‘‹", "π‘‹", "π‘‹‘", "π‘‹’", "π‘‹“", "π‘‹”", "π‘‹–", "π‘‹—", "π‘‹", "π‘‹™", "π‘‹", "π‘‹›", "π‘‹", "π‘‹π‘‹©", "π‘‹", "π‘‹", "π‘‹π‘‹©", "π‘Ίπ‘‹π‘‹π‘‹©", "π‘‹‚π‘‹π‘‹…",]
symbols = [ "π‘‹°", "π‘‹±", "π‘‹²", "π‘‹³", "π‘‹΄", "π‘‹µ", "π‘‹¶", "π‘‹·", "π‘‹Έ", "π‘‹Ή", "π‘Έπ‘‹", "ΰ¤½", "ΰ¥¤", "ΰ¥¥",]
candra = [ "π‘‹¥",]
