[vowels]
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เฅ" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เฅก" = "๐ฉ๐ฉ"
"เค" = ""
"เค" = "๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = ""
"เค" = "๐ฉ"
"เค" = "๐ฉ"

[vowel_marks]
"เคพ" = "๐ฉ"
"เคฟ" = "๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ๐ฉ"
"เฅ" = "๐ฉ๐ฉ"
"เฅข" = "๐ฉ๐ฉ"
"เฅฃ" = "๐ฉ๐ฉ"
"เฅ" = ""
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ๐ฉ"
"เฅ" = ""
"เฅ" = "๐ฉ"
"เฅ" = "๐ฉ"

[yogavaahas]
"เค" = "๐ฉ"
"เค" = "๐ฉ"
"เค" = "๐ฉ"

[virama]
"เฅ" = ""

[consonants]
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เค" = "๐ฉ๐ฉ"
"เคก" = "๐ฉ๐ฉ"
"เคข" = "๐ฉ๐ฉ"
"เคฃ" = "๐ฉ๐ฉ"
"เคค" = "๐ฉ๐ฉ"
"เคฅ" = "๐ฉ๐ฉ"
"เคฆ" = "๐ฉ๐ฉ"
"เคง" = "๐ฉ๐ฉ"
"เคจ" = "๐ฉ๐ฉ"
"เคช" = "๐ฉ๐ฉ"
"เคซ" = "๐ฉ๐ฉ"
"เคฌ" = "๐ฉ๐ฉ"
"เคญ" = "๐ฉ๐ฉ"
"เคฎ" = "๐ฉ๐ฉ"
"เคฏ" = "๐ฉ๐ฉ"
"เคฐ" = "๐ฉ๐ฉ"
"เคฒ" = "๐ฉ๐ฉ"
"เคต" = "๐ฉ๐ฉ"
"เคถ" = "๐ฉ๐ฉ"
"เคท" = "๐ฉ๐ฉ"
"เคธ" = "๐ฉ๐ฉ"
"เคน" = "๐ฉ๐ฉ"
"เคณ" = "๐ฉ๐ฉ"
"เคเฅเคท" = "๐ฉ๐ฉ๐ฉ"
"เคเฅเค" = "๐ฉ๐ฉ๐ฉ"

[symbols]
"เฅฆ" = "๐ฉ"
"เฅง" = "๐ฉก"
"เฅจ" = "๐ฉข"
"เฅฉ" = "๐ฉฃ"
"เฅช" = "๐ฉค"
"เฅซ" = "๐ฉฅ"
"เฅฌ" = "๐ฉฆ"
"เฅญ" = "๐ฉง"
"เฅฎ" = "๐ฉจ"
"เฅฏ" = "๐ฉฉ"
"เฅ" = "๐ฉ๐ฉ"
"เคฝ" = ""
"เฅค" = "เฅค"
"เฅฅ" = "เฅฅ"

[candra]
"เฅ" = "๐ฉ"
