vowels = [ "ğ‘€", "ğ‘", "ğ‘‚", "ğ‘ƒ", "ğ‘„", "ğ‘…", "ğ‘†", "ğ‘‡", "ğ‘ˆ", "ğ‘‰", "", "ğ‘Š", "ğ‘‹", "", "ğ‘Œ", "ğ‘",]
vowel_marks = [ "ğ‘µ", "ğ‘¶", "ğ‘·", "ğ‘¸", "ğ‘¹", "ğ‘º", "ğ‘»", "ğ‘¼", "ğ‘½", "", "ğ‘¾", "ğ‘¿", "", "ğ‘‘€", "ğ‘‘",]
yogavaahas = [ "ğ‘‘„", "ğ‘‘…", "ğ‘‘ƒ",]
virama = [ "ğ‘‘‚",]
consonants = [ "ğ‘", "ğ‘", "ğ‘", "ğ‘‘", "ğ‘’", "ğ‘”", "ğ‘•", "ğ‘–", "ğ‘—", "ğ‘˜", "ğ‘š", "ğ‘›", "ğ‘œ", "ğ‘", "ğ‘", "ğ‘Ÿ", "ğ‘ ", "ğ‘¡", "ğ‘¢", "ğ‘£", "ğ‘¥", "ğ‘¦", "ğ‘§", "ğ‘¨", "ğ‘©", "ğ‘«", "ğ‘¬", "ğ‘®", "ğ‘°", "ğ‘±", "ğ‘²", "ğ‘³", "ğ‘´", "ğ‘®ğ‘‘†", "ğ‘ğ‘‘‚ğ‘²", "ğ‘–ğ‘‘‚ğ‘˜",]
symbols = [ "ğ‘‘", "ğ‘‘‘", "ğ‘‘’", "ğ‘‘“", "ğ‘‘”", "ğ‘‘•", "ğ‘‘–", "ğ‘‘—", "ğ‘‘˜", "ğ‘‘™", "ğ‘‘‰", "ğ‘‘‡", "à¥¤", "à¥¥",]
candra = [ "ğ‘¾",]
