vowels = [ "ğ‘ƒ¦ğ‘ƒ¨", "ğ‘ƒ¢", "ğ‘ƒ¤", "ğ‘ƒ¤", "ğ‘ƒ¥", "ğ‘ƒ¥", "ğ‘ƒğ‘ƒ¤", "ğ‘ƒğ‘ƒ¤", "ğ‘ƒ˜ğ‘ƒ¤", "ğ‘ƒ˜ğ‘ƒ¤", "ğ‘ƒ£", "ğ‘ƒ£", "ğ‘ƒ§", "ğ‘ƒ¦", "ğ‘ƒ¦", "ğ‘ƒ¦ğ‘ƒ¥",]
vowel_marks = [ "ğ‘ƒ¢", "ğ‘ƒ¤", "ğ‘ƒ¤", "ğ‘ƒ¥", "ğ‘ƒ¥", "ğ‘ƒğ‘ƒ¤", "ğ‘ƒğ‘ƒ¤", "ğ‘ƒ˜ğ‘ƒ¤", "ğ‘ƒ˜ğ‘ƒ¤", "ğ‘ƒ£", "ğ‘ƒ£", "ğ‘ƒ§", "ğ‘ƒ¦", "ğ‘ƒ¦", "ğ‘ƒ¦ğ‘ƒ¥",]
yogavaahas = [ "ğ‘ƒ–", "ğ‘ƒ", "ğ‘ƒ–",]
virama = [ "",]
consonants = [ "ğ‘ƒŸ", "ğ‘ƒŸğ‘ƒ ", "ğ‘ƒ•", "ğ‘ƒ•ğ‘ƒ ", "ğ‘ƒ—", "ğ‘ƒ“", "ğ‘ƒ“ğ‘ƒ ", "ğ‘ƒ ", "ğ‘ƒ ğ‘ƒ ", "ğ‘ƒ¡", "ğ‘ƒ‘ğ‘ƒ¨", "ğ‘ƒ‘ğ‘ƒ¨ğ‘ƒ ", "ğ‘ƒ”", "ğ‘ƒ”ğ‘ƒ ", "ğ‘ƒ™ğ‘ƒ¨", "ğ‘ƒ‘", "ğ‘ƒ‘ğ‘ƒ ", "ğ‘ƒ”ğ‘ƒ¨", "ğ‘ƒ”ğ‘ƒ¨ğ‘ƒ ", "ğ‘ƒ™", "ğ‘ƒ›", "ğ‘ƒ›ğ‘ƒ ", "ğ‘ƒ’", "ğ‘ƒ’ğ‘ƒ ", "ğ‘ƒ–", "ğ‘ƒœ", "ğ‘ƒ", "ğ‘ƒ˜", "ğ‘ƒš", "ğ‘ƒğ‘ƒ ", "ğ‘ƒğ‘ƒ¨", "ğ‘ƒ", "ğ‘ƒ", "ğ‘ƒ˜ğ‘ƒ¨", "ğ‘ƒŸğ‘ƒğ‘ƒ¨", "ğ‘ƒ ğ‘ƒ¡",]
symbols = [ "ğ‘ƒ°", "ğ‘ƒ±", "ğ‘ƒ²", "ğ‘ƒ³", "ğ‘ƒ´", "ğ‘ƒµ", "ğ‘ƒ¶", "ğ‘ƒ·", "ğ‘ƒ¸", "ğ‘ƒ¹", "ğ‘ƒ¦ğ‘ƒ–", "'", ".", "..",]
candra = [ "ğ‘ƒ£",]
extra_consonants = [ "ğ‘ƒŸ", "ğ‘ƒŸğ‘ƒ ", "ğ‘ƒ•", "ğ‘ƒ ", "ğ‘ƒğ‘ƒ”", "ğ‘ƒğ‘ƒ”ğ‘ƒ ", "ğ‘ƒ›ğ‘ƒ ", "ğ‘ƒœ", "ğ‘ƒ˜",]
