vowels = [ "ğ‘š€", "ğ‘š", "ğ‘š‚", "ğ‘šƒ", "ğ‘š„", "ğ‘š…", "ğ‘š¤ğ‘š®", "ğ‘š¤ğ‘š¯", "ğ‘š¥ğ‘š®", "ğ‘š¥ğ‘š¯", "ğ‘š†", "ğ‘š†", "ğ‘š‡", "ğ‘šˆ", "ğ‘šˆ", "ğ‘š‰",]
vowel_marks = [ "ğ‘š­", "ğ‘š®", "ğ‘š¯", "ğ‘š°", "ğ‘š±", "ğ‘š¶ğ‘š¤ğ‘š®", "ğ‘š¶ğ‘š¤ğ‘š¯", "ğ‘š¶ğ‘š¥ğ‘š®", "ğ‘š¶ğ‘š¥ğ‘š¯", "ğ‘š³", "ğ‘š²", "ğ‘š³", "ğ‘š´", "ğ‘š´", "ğ‘šµ",]
yogavaahas = [ "ğ‘š«", "ğ‘š¬", "ğ‘š«",]
virama = [ "ğ‘š¶",]
consonants = [ "ğ‘šŠ", "ğ‘š‹", "ğ‘šŒ", "ğ‘š", "ğ‘š", "ğ‘š", "ğ‘š", "ğ‘š‘", "ğ‘š’", "ğ‘š“", "ğ‘š”", "ğ‘š•", "ğ‘š–", "ğ‘š—", "ğ‘š˜", "ğ‘š™", "ğ‘šš", "ğ‘š›", "ğ‘šœ", "ğ‘š", "ğ‘š", "ğ‘šŸ", "ğ‘š ", "ğ‘š¡", "ğ‘š¢", "ğ‘š£", "ğ‘š¤", "ğ‘š¥", "ğ‘š¦", "ğ‘š§", "ğ‘š‹", "ğ‘š¨", "ğ‘š©", "ğ‘š¥ğ‘š·", "ğ‘šŠğ‘š¶ğ‘š‹", "ğ‘š‘ğ‘š¶ğ‘š“",]
symbols = [ "ğ‘›€", "ğ‘›", "ğ‘›‚", "ğ‘›ƒ", "ğ‘›„", "ğ‘›…", "ğ‘›†", "ğ‘›‡", "ğ‘›ˆ", "ğ‘›‰", "ğ‘šˆğ‘š«", "à¤½", "à¥¤", "à¥¥",]
candra = [ "ğ‘š³",]
extra_consonants = [ "ğ‘šŠğ‘š·", "ğ‘š‹ğ‘š·", "ğ‘šŒğ‘š·", "ğ‘š‘ğ‘š·", "ğ‘šª", "ğ‘š—ğ‘š·", "ğ‘šŸğ‘š·", "ğ‘š£ğ‘š·", "ğ‘š¤ğ‘š·",]
