vowels = [ "ğ‘’", "ğ‘’‚", "ğ‘’ƒ", "ğ‘’„", "ğ‘’…", "ğ‘’†", "ğ‘’‡", "ğ‘’ˆ", "ğ‘’‰", "ğ‘’Š", "ğ‘’ğ‘’º", "ğ‘’‹", "ğ‘’Œ", "ğ‘’ğ‘’½", "ğ‘’", "ğ‘’",]
vowel_marks = [ "ğ‘’°", "ğ‘’±", "ğ‘’²", "ğ‘’³", "ğ‘’´", "ğ‘’µ", "ğ‘’¶", "ğ‘’·", "ğ‘’¸", "ğ‘’º", "ğ‘’¹", "ğ‘’»", "ğ‘’½", "ğ‘’¼", "ğ‘’¾",]
yogavaahas = [ "ğ‘“€", "ğ‘“", "ğ‘’¿",]
virama = [ "ğ‘“‚",]
consonants = [ "ğ‘’", "ğ‘’", "ğ‘’‘", "ğ‘’’", "ğ‘’“", "ğ‘’”", "ğ‘’•", "ğ‘’–", "ğ‘’—", "ğ‘’˜", "ğ‘’™", "ğ‘’š", "ğ‘’›", "ğ‘’œ", "ğ‘’", "ğ‘’", "ğ‘’Ÿ", "ğ‘’ ", "ğ‘’¡", "ğ‘’¢", "ğ‘’£", "ğ‘’¤", "ğ‘’¥", "ğ‘’¦", "ğ‘’§", "ğ‘’¨", "ğ‘’©", "ğ‘’ª", "ğ‘’«", "ğ‘’¬", "ğ‘’­", "ğ‘’®", "ğ‘’¯", "ğ‘’ğ‘“ƒ", "ğ‘’ğ‘“‚ğ‘’­", "ğ‘’–ğ‘“‚ğ‘’˜",]
symbols = [ "ğ‘“", "ğ‘“‘", "ğ‘“’", "ğ‘““", "ğ‘“”", "ğ‘“•", "ğ‘“–", "ğ‘“—", "ğ‘“˜", "ğ‘“™", "ğ‘“‡", "ğ‘“„", "à¥¤", "à¥¥",]
candra = [ "ğ‘’¹",]
extra_consonants = [ "ğ‘’ğ‘“ƒ", "ğ‘’ğ‘“ƒ", "ğ‘’‘ğ‘“ƒ", "ğ‘’–ğ‘“ƒ", "ğ‘’›ğ‘“ƒ", "ğ‘’œğ‘“ƒ", "ğ‘’¤ğ‘“ƒ", "ğ‘’¨ğ‘“ƒ", "ğ‘’©",]
