vowels = [ "ğ‘£", "ğ‘£ğ‘£™", "ğ‘£‚", "ğ‘£†", "ğ‘£ƒ", "ğ‘£‡", "ğ‘£œğ‘£ƒ", "ğ‘£œğ‘£‡", "ğ‘£šğ‘£ƒ", "ğ‘£šğ‘£‡", "ğ‘£ˆ", "ğ‘£ˆ", "ğ‘£†", "ğ‘£‰", "ğ‘£‰", "ğ‘£‡",]
vowel_marks = [ "ğ‘£ğ‘£™", "ğ‘£‚", "ğ‘£†", "ğ‘£ƒ", "ğ‘£‡", "ğ‘£œğ‘£ƒ", "ğ‘£œğ‘£‡", "ğ‘£šğ‘£ƒ", "ğ‘£šğ‘£‡", "ğ‘£ˆ", "ğ‘£ˆ", "ğ‘£†", "ğ‘£‰", "ğ‘£‰", "ğ‘£‡",]
yogavaahas = [ "ğ‘£€", "ğ‘£„", "ğ‘£€",]
virama = [ "",]
consonants = [ "ğ‘£Œ", "ğ‘£Œ", "ğ‘£‹", "ğ‘£‹", "ğ‘£Š", "ğ‘£", "ğ‘£", "ğ‘£", "ğ‘£", "ğ‘£", "ğ‘£’", "ğ‘£’", "ğ‘£‘", "ğ‘£‘", "ğ‘£", "ğ‘£•", "ğ‘£•", "ğ‘£”", "ğ‘£”", "ğ‘£“", "ğ‘£˜", "ğ‘£˜", "ğ‘£—", "ğ‘£—", "ğ‘£–", "ğ‘£…", "ğ‘£œ", "ğ‘£š", "ğ‘£Ÿ", "ğ‘£", "ğ‘£", "ğ‘£", "ğ‘£™", "ğ‘£š", "ğ‘£Œğ‘£", "ğ‘£ğ‘£",]
symbols = [ "ğ‘£ ", "ğ‘£¡", "ğ‘£¢", "ğ‘££", "ğ‘£¤", "ğ‘£¥", "ğ‘£¦", "ğ‘£§", "ğ‘£¨", "ğ‘£©", "ğ‘£¿", "'", ".", "..",]
candra = [ "ğ‘£ˆ",]
extra_consonants = [ "ğ‘£Œ", "ğ‘£Œ", "ğ‘£‹", "ğ‘£", "ğ‘£›", "ğ‘£›", "ğ‘£˜", "ğ‘£…", "ğ‘£œ",]
