vowels = [ "ğ¬€", "ğ¬", "ğ¬Œ", "ğ¬", "ğ¬", "ğ¬", "ğ¬†ğ¬­ğ¬†", "ğ¬‡ğ¬­ğ¬‡", "ğ¬†ğ¬®ğ¬†", "ğ¬‡ğ¬®ğ¬‡", "ğ¬ˆ", "ğ¬‰", "ğ¬€ğ¬Œ", "ğ¬Š", "ğ¬‹", "ğ¬€ğ¬",]
vowel_marks = [ "ğ¬", "ğ¬Œ", "ğ¬", "ğ¬", "ğ¬", "ğ¬†ğ¬­ğ¬†", "ğ¬‡ğ¬­ğ¬‡", "ğ¬†ğ¬®ğ¬†", "ğ¬‡ğ¬®ğ¬‡", "ğ¬ˆ", "ğ¬‰", "ğ¬€ğ¬Œ", "ğ¬Š", "ğ¬‹", "ğ¬€ğ¬",]
yogavaahas = [ "ğ¬©", "ğ¬µ", "ğ¬©",]
virama = [ "",]
consonants = [ "ğ¬ğ¬€", "ğ¬‘ğ¬€", "ğ¬”ğ¬€", "ğ¬–ğ¬€", "ğ¬¢ğ¬€", "ğ¬—ğ¬€", "ğ¬—ğ¬€", "ğ¬˜ğ¬€", "ğ¬˜ğ¬€", "ğ¬¦ğ¬€", "ğ¬™ğ¬€", "ğ¬šğ¬€", "ğ¬›ğ¬€", "ğ¬›ğ¬€", "ğ¬§ğ¬€", "ğ¬™ğ¬€", "ğ¬šğ¬€", "ğ¬›ğ¬€", "ğ¬œğ¬€", "ğ¬¥ğ¬€", "ğ¬ğ¬€", "ğ¬ğ¬€", "ğ¬ ğ¬€", "ğ¬ ğ¬€", "ğ¬¨ğ¬€", "ğ¬«ğ¬€", "ğ¬­ğ¬€", "ğ¬®ğ¬€", "ğ¬¬ğ¬€", "ğ¬±ğ¬€", "ğ¬´ğ¬€", "ğ¬¯ğ¬€", "ğ¬µğ¬€", "ğ¬®ğ¬€", "ğ¬ğ¬´ğ¬€", "ğ¬˜ğ¬¦ğ¬€",]
symbols = [ "0", "1", "2", "3", "4", "5", "6", "7", "8", "9", "ğ¬‹ğ¬¨", "", "ğ¬¼\u200f", "ğ¬½\u200f",]
zwj = [ "\u200d",]
skip = [ "",]
accents = [ "à¥‘", "à¥’",]
candra = [ "ğ¬‰",]
extra_consonants = [ "ğ¬ğ¬€", "ğ¬“ğ¬€", "ğ¬•ğ¬€", "ğ¬°ğ¬€", "ğ¬›ğ¬€", "ğ¬œğ¬€", "ğ¬Ÿğ¬€", "ğ¬ªğ¬€", "ğ¬­ğ¬€",]
