vowels = [ "ğ‘Š€", "ğ‘Š€", "ğ‘Š", "ğ‘Š", "ğ‘Š‚", "ğ‘Š‚", "ğ‘Š¢ğ‘Š‚", "ğ‘Š¢ğ‘Š‚", "ğ‘Š£ğ‘Š‚", "ğ‘Š£ğ‘Š‚", "", "ğ‘Šƒ", "ğ‘Šƒ", "", "ğ‘Š‚", "ğ‘Š‚",]
yogavaahas = [ "ğ‘Šš", "ğ‘Š¦", "ğ‘Šš",]
virama = [ "",]
consonants = [ "ğ‘Š„", "ğ‘Š…", "ğ‘Š†", "ğ‘Šˆ", "ğ‘Šš", "ğ‘ŠŠ", "ğ‘Š‹", "ğ‘ŠŒ", "ğ‘ŠŒ", "ğ‘Š", "ğ‘Š", "ğ‘Š‘", "ğ‘Š’", "ğ‘Š”", "ğ‘Š•", "ğ‘Š–", "ğ‘Š—", "ğ‘Š˜", "ğ‘Š™", "ğ‘Šš", "ğ‘Š›", "ğ‘Šœ", "ğ‘Š", "ğ‘ŠŸ", "ğ‘Š ", "ğ‘Š¡", "ğ‘Š¢", "ğ‘Š£", "ğ‘Š¤", "ğ‘Š¥", "ğ‘Š¥", "ğ‘Š¥", "ğ‘Š¦", "ğ‘Š£", "ğ‘Š„ğ‘Š¥", "ğ‘ŠŒğ‘Š",]
symbols = [ "à©¦", "à©§", "à©¨", "à©©", "à©ª", "à©«", "à©¬", "à©­", "à©®", "à©¯", "ğ‘Š‚ğ‘Š ", "", "à¥¤", "à¥¥",]
candra = [ "ğ‘Šƒ",]
